language: php

php:
  - '5.6'
  - '7.0'

#install:
#  - curl -s http://getcomposer.org/installer | php
#  - php composer.phar install --dev --no-interaction
#  - composer dump-autoload
#
#script:
#  - mkdir -p build/cov
#  - mkdir -p build/logs
#  - php vendor/bin/phpunit -c phpunit.dist.xml
#
#after_success:
#  - travis_retry php vendor/bin/coveralls -v
#  - travis_retry php vendor/bin/codacycoverage clover build/logs/clover.xml
#